module.exports.data = JSON.stringify([ { slack_channel_name: '',
company_name: 'ムラマツ住設',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社ムラマツ住設' },
{ slack_channel_name: '',
company_name: 'タニムラ設備',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社タニムラ設備' },
{ slack_channel_name: '',
company_name: 'かりゆし運送',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社かりゆし運送' },
{ slack_channel_name: '',
company_name: '若林組',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社若林組' },
{ slack_channel_name: '',
company_name: '喜多建設',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社喜多建設' },
{ slack_channel_name: '',
company_name: 'リスタートクリーン',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社リスタートクリーン' },
{ slack_channel_name: '',
company_name: 'カイゴー',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社カイゴー' },
{ slack_channel_name: '',
company_name: '学校法人暁星学園',
co_ltd_inc_etc: '',
position: '',
official_company_name: '学校法人暁星学園' },
{ slack_channel_name: '',
company_name: '榎本工業',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: '榎本工業株式会社' },
{ slack_channel_name: '',
company_name: '吉田架設',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社吉田架設' },
{ slack_channel_name: '',
company_name: 'コナップ',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社コナップ' },
{ slack_channel_name: '',
company_name: 'HARU',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社HARU' },
{ slack_channel_name: '',
company_name: 'ＳＥＩＺＡＮ',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社ＳＥＩＺＡＮ' },
{ slack_channel_name: '',
company_name: '愛京鈑金工業所',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社愛京鈑金工業所' },
{ slack_channel_name: '',
company_name: '騰',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社騰' },
{ slack_channel_name: '',
company_name: 'ツールデザイン',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社ツールデザイン' },
{ slack_channel_name: '',
company_name: '栄光プロテック',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: '栄光プロテック株式会社' },
{ slack_channel_name: '',
company_name: '千尋海洋技術',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: '千尋海洋技術株式会社' },
{ slack_channel_name: '',
company_name: 'エムアンドワイ',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社エムアンドワイ' },
{ slack_channel_name: '',
company_name: 'Ｚａｃ',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社Ｚａｃ' },
{ slack_channel_name: '',
company_name: '佐伯架設',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社佐伯架設' },
{ slack_channel_name: '',
company_name: ' エストワン',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社 エストワン' },
{ slack_channel_name: '',
company_name: '阿部住設工業',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社阿部住設工業' },
{ slack_channel_name: '',
company_name: '丸和朝日酸素工業所',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社丸和朝日酸素工業所' },
{ slack_channel_name: 'p0366_no1_okinaka',
company_name: '沖中基礎',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社沖中基礎' },
{ slack_channel_name: '',
company_name: 'グローバルスタイル',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社グローバルスタイル' },
{ slack_channel_name: '',
company_name: 'メディアクロス',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社メディアクロス' },
{ slack_channel_name: '',
company_name: '共栄プランニング',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社共栄プランニング' },
{ slack_channel_name: '',
company_name: 'トータル',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社トータル' },
{ slack_channel_name: '',
company_name: 'テクノユニテック',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: 'テクノユニテック株式会社' },
{ slack_channel_name: '',
company_name: 'コニデン',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社コニデン' },
{ slack_channel_name: '',
company_name: '晴輝工業',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社晴輝工業' },
{ slack_channel_name: 'p0388_no1_tomoikikai',
company_name: '社会福祉法人ともいき会',
co_ltd_inc_etc: '',
position: '',
official_company_name: '社会福祉法人ともいき会' },
{ slack_channel_name: '',
company_name: '京和工業',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: '京和工業株式会社' },
{ slack_channel_name: '',
company_name: '辻運輸',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社辻運輸' },
{ slack_channel_name: '',
company_name: 'ドライサポートアンドサービス',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社ドライサポートアンドサービス' },
{ slack_channel_name: '',
company_name: 'オールクリーン',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社オールクリーン' },
{ slack_channel_name: 'p0409_no1_touri9',
company_name: '東陸運輸',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社東陸運輸' },
{ slack_channel_name: '',
company_name: '巧力工業',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社巧力工業' },
{ slack_channel_name: 'p0405_no1_toryo',
company_name: '東菱機工',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社東菱機工' },
{ slack_channel_name: 'p0414_no1_tanaka',
company_name: '田中電工',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: '田中電工株式会社' },
{ slack_channel_name: 'p0418_no1_mjs ',
company_name: 'MJS',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社MJS' },
{ slack_channel_name: 'p0412_no1_pleasurework',
company_name: 'プレジャーワーク',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: 'プレジャーワーク株式会社' },
{ slack_channel_name: 'p0422_no1_munakata',
company_name: 'ムナカタ工業',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社ムナカタ工業' },
{ slack_channel_name: 'p0423_no1_es',
company_name: "e's",
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: "株式会社e's" },
{ slack_channel_name: 'p0428_no1_oguma',
company_name: '小熊工業',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社小熊工業' },
{ slack_channel_name: 'p0426_no1_ogatahoon',
company_name: '尾形保温',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社尾形保温' },
{ slack_channel_name: 'p0438_no1_earth',
company_name: 'Earth',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社Earth' },
{ slack_channel_name: 'p0431_no1_verdy',
company_name: 'ヴェルディ・メタル・サービス',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社ヴェルディ・メタル・サービス' },
{ slack_channel_name: 'p0483_no1_murakami',
company_name: '村上建設',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社村上建設' },
{ slack_channel_name: 'p0442_no1_uezono',
company_name: '上園工務店',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社上園工務店' },
{ slack_channel_name: 'p0445_no1_ikeda',
company_name: 'イケダ空調工業',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: 'イケダ空調工業株式会社' },
{ slack_channel_name: 'p0446_no1_toho',
company_name: '東豊',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社東豊' },
{ slack_channel_name: 'p0449_no1_kenex',
company_name: 'ケンエキスプレス',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社ケンエキスプレス' },
{ slack_channel_name: 'p0443_no1_rooftop',
company_name: 'ROOF TOP',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社ROOF TOP' },
{ slack_channel_name: 'p0473_no1_ogawa',
company_name: 'オガワ工業',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社オガワ工業' },
{ slack_channel_name: 'p0459_no1_seisen',
company_name: '政泉',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社政泉' },
{ slack_channel_name: 'p0476_no1_abe',
company_name: '阿部工業',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: '阿部工業株式会社' },
{ slack_channel_name: 'p0480_no1_fujikikougyou',
company_name: 'フジ喜工業',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社フジ喜工業' },
{ slack_channel_name: 'p0461_no1_tsunakawa',
company_name: '綱川建設',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社綱川建設' },
{ slack_channel_name: 'p0488_no1_taihei',
company_name: '泰平ライジング',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社泰平ライジング' },
{ slack_channel_name: 'p0495_no1_raiki',
company_name: '来紀工業',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社来紀工業' },
{ slack_channel_name: 'p0483_no1_murakami',
company_name: '村上建設',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社村上建設' },
{ slack_channel_name: 'p0493_no1_itodenkosya',
company_name: '伊藤電工社',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社伊藤電工社' },
{ slack_channel_name: 'p0502_no1_elite',
company_name: 'ELITE',
co_ltd_inc_etc: '株式会社',
position: 'after',
official_company_name: 'ELITE株式会社' },
{ slack_channel_name: 'p0504_no1_maeda',
company_name: '前田内装',
co_ltd_inc_etc: '',
position: '',
official_company_name: '前田内装' },
{ slack_channel_name: 'p0506_no1_sanei',
company_name: '讃栄建設',
co_ltd_inc_etc: '有限会社',
position: 'before',
official_company_name: '有限会社讃栄建設' },
{ slack_channel_name: 'p0512_no1_yuken',
company_name: '祐健',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社祐健' },
{ slack_channel_name: 'p0508_no1_kinoshita',
company_name: 'インテリア木下',
co_ltd_inc_etc: '株式会社',
position: 'before',
official_company_name: '株式会社インテリア木下' } ]);